spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: heybetmovlamov2005@gmail.com
    password: shqj qdts kxkw lngf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 3000
          timeout: 3000
          writetimeout: 3000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8085

logging:
  level:
    org.springframework.web: DEBUG
